name: Repo Traffic Back Up
on:
  schedule: 
    # Runs every week
    - cron: "0 0 */7 * *"
    
jobs:
  # This workflow stores repository traffic and clones past the default 2 week period
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: "traffic"
    
    # Calculates traffic and clones and stores them in a CSV file
    # This workflow is based on https://github.com/marketplace/actions/repository-traffic
    - name: GitHub traffic 
      uses: sangonzal/repository-traffic-action@v.0.1.6
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
     
    # Commits files to traffic branch
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Laura Luebbert
        message: "GitHub traffic"
        add: "./traffic/*"
        ref: "traffic"
